spring.datasource.url=jdbc:postgresql://localhost:15432/sentinel
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

sentinel.api.key=7b2c8a9f-3e4d-4a1b-9c8d-7e6f5a4b3c2d

management.endpoints.web.base-path=/actuator
management.endpoints.web.exposure.include=health,info,metrics,prometheus,flyway,loggers,env
management.endpoint.health.show-details=always
management.endpoint.prometheus.enabled=true
management.info.env.enabled=true

info.app.name=Sentinel API
info.app.version=0.0.1

management.metrics.tags.application=sentinel-api