spring.datasource.url=jdbc:postgresql://127.0.0.1:15432/sentinel_db?sslmode=disable&gssEncMode=disable
spring.datasource.username=admin
spring.datasource.password=adminpassword

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false