### New Machine (POST)
POST http://localhost:8080/api/machines
Content-Type: application/json

{
  "hostname": "PC-GABINETE-01",
  "ipAddress": "192.168.0.15",
  "os": "Windows 11",
  "status": "ONLINE"
}

### Get All Machines (GET)
GET http://localhost:8080/api/machines

### Get Machines with ID 1
GET http://localhost:8080/api/machines/3

### Patch Machine with ID 1
PUT http://localhost:8080/api/machines/3
Content-Type: application/json

{
  "hostname": "PC-GABINETE-01-REVISADO",
  "ipAddress": "192.168.0.15",
  "os": "Windows 11",
  "status": "OFFLINE"
}

### Delete Machine ID 1
DELETE http://localhost:8080/api/machines/1

### Create Task for Machine Id
POST http://localhost:8080/api/tasks/machine/4
Content-Type: application/json

{
  "command": "ping 8.8.8.8",
  "status": "PENDING"
}

### Agent of Machine 4 asks for pending tasks
GET http://localhost:8080/api/tasks/machine/4/pending

### Agent notificate that task 1 is completed
PUT http://localhost:8080/api/tasks/1/status
Content-Type: application/json

{
  "status": "COMPLETED"
}

###  Agent warns that it stopped
PUT http://localhost:8080/api/tasks/1/status
Content-Type: application/json

{
  "status": "COMPLETED",
  "outputLog": "Shooting against 8.8.8.8 com 32 bytes of data:\nResponse from 8.8.8.8: bytes=32 time=14ms TTL=117\nResponse from 8.8.8.8: bytes=32 time=15ms TTL=117\n\nPing Statistics para 8.8.8.8:\nPackages: Send = 2, Received = 2, Lost = 0"
}

### Agent Registration Test
POST http://localhost:8080/api/machines/register
Content-Type: application/json

{
  "hostname": "DESKTOP-COMMANDER",
  "os": "Windows 11"
}